version: '3'

services:
  web:
    build: .
    command: bash -c "
      uvicorn app:app
      --host localhost --port 8000
      --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"